version: '3'
services:
  api:
   image: informasjonsforvaltning/example-api:latest
   ports:
    - "8080:8080"
  telegraf:
    image: "telegraf:latest"
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
  influxdb:
    image: influxdb:latest
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    depends_on:
      - telegraf
  kapacitor:
    image: "kapacitor:latest"
    ports:
      - "9092:9092"
    environment:
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
    depends_on:
      - influxdb
  chronograf:
    image: "chronograf:latest"
    ports:
      - "8888:8888"
    depends_on:
      - influxdb
      - kapacitor
