version: '3'
services:
 api:
   image: informasjonsforvaltning/example-api:lates
   ports:
    - "8080:8080"
  influxdb:
    image: influxdb:latest
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
  telegraf:
    image: "telegraf:latest"
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    ports:
      - "8125:8125"
    depends_on:
      - influxdb
  grafana:
    image: "grafana/grafana:latest"
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
