apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: chronograf
  name: chronograf
spec:
  ports:
  - name: "8888"
    port: 8888
    targetPort: 8888
  - name: "8080"
    port: 8080
    targetPort: 8888
  selector:
    io.kompose.service: chronograf
status:
  loadBalancer: {}
