apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    fdk.service: influxdb
  name: influxdb
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  type: NodePort
  ports:
  - name: "8083"
    port: 8083
    targetPort: 8083
  - name: "8086"
    port: 8086
    targetPort: 8086
  - name: "8090"
    port: 8090
    targetPort: 8090
  - name: "8080"
    port: 8080
    targetPort: 8086
  selector:
    fdk.service: influxdb
status:
  loadBalancer: {}
