apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    fdk.service: kapacitor
  name: kapacitor
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  type: NodePort
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    fdk.service: kapacitor
status:
  loadBalancer: {}
