apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    fdk.service: kapacitor
  name: kapacitor
spec:
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
  selector:
    fdk.service: kapacitor
status:
  loadBalancer: {}
