apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    fdk.service: telegraf
  name: telegraf
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    fdk.service: telegraf
status:
  loadBalancer: {}
