apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    fdk.service: telegraf
  name: telegraf
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      fdk.service: telegraf
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        fdk.service: telegraf
    spec:
      containers:
        name: telegraf
        image: telegraf:latest
        env:
        - name: NAMESPACE
          valueFrom:
            secretKeyRef:
              name: commonurl-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: NAMESPACE
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: {{ required "Missing value TELEGRAF_MEMORY" .Values.TELEGRAF_MEMORY | quote }}
        volumeMounts:
        - mountPath: /etc/telegraf/telegraf.conf
          name: telegraf-claim0
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: telegraf-claim0
        persistentVolumeClaim:
          claimName: telegraf-claim0
          readOnly: true
status: {}
