apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    fdk.service: telegraf
  name: telegraf
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        fdk.service: telegraf
    spec:
      containers:
      - image: telegraf:latest
        name: telegraf
        resources: {}
        volumeMounts:
        - mountPath: /etc/telegraf/telegraf.conf
          name: telegraf-claim0
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: telegraf-claim0
        persistentVolumeClaim:
          claimName: telegraf-claim0
          readOnly: true
status: {}
