# Default values for the TICK stack.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

##chronograf
CHRONOGRAF_MEMORY: "500Mi"

##influxdb
INFLUXDB_MEMORY: "500Mi"

##kapacitor
KAPACITOR_MEMORY: "500Mi"

##telegraf
TELEGRAF_MEMORY: "500Mi"